### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/deploy#25]
Building with SBCL 2.4.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 80aeaae2e54aa8887ebeca45fd977a6cf852ab49

*deploy-test* fails to build with the following error:

```
Unhandled ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR in thread #<SB-THREAD:THREAD tid=926982 "main thread" RUNNING {1000DC8003}>: Error while trying to load definition for system deploy-test from pathname /home/quicklisp/quicklisp-controller/dist/build-cache/deploy/7580fd26d8d084e255926f97167279503994c7dd/deploy-20240730-git/deploy-test.asd: The function DEPLOY::REMAVE is undefined.

```

*deploy* fails to build with the following error:

```
Unhandled UNDEFINED-FUNCTION in thread #<SB-THREAD:THREAD tid=926986 "main thread" RUNNING {1000DC8003}>: The function DEPLOY::REMAVE is undefined.

```

[Full log here](http://report.quicklisp.org/2024-07-30/failure-report/deploy.html)

**Comment by Shinmera** [comment]
This was already fixed four days ago. The commit you are on is not part of the proper history anymore, as it was force-pushed away.

This isn't the first time this sort of issue has happened, either. Please make sure that quicklisp uses a fetch+reset strategy rather than a pull strategy when updating sources. Otherwise it is liable to get stuck on orphaned commits just like it did here.

**Comment by quicklisp** [comment]
Thanks for the info. I'll update the software to use fetch+reset sometime.
